---

## Install openjdk

- name: Install openjdk packages and dependencies
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - openjdk-8-jre-headless

## mongodb

- name: Adding the MongoDB PPA
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    update_cache: "{{ update_apt_cache }}"
    state: present

- name: Add an MongoDB apt key from keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: Add mongodb-org repository into sources list.
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    state: present

- name: Install MongoDB
  apt: name=mongodb-org state=installed

- name: Ensure MongoDB is started and enabled to start at boot.
  service: name=mongod state=started enabled=yes

## Install elasticsearch

- name: Add the ElasticSearch public GPG key to the apt repo
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add ElasticSearch to the trusted sources list
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    update_cache: "{{ update_apt_cache }}"
    state: present

- name: Install ElasticSearch
  apt: name=elasticsearch state=installed

- name: Adding existing user 'elasticsearch' to group graylog
  user: name='elasticsearch'
        groups=graylog
        append=yes

#- name: Copy the ElasticSearch configuration file
#  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=elasticsearch mode=0750 force=yes
#  notify: restart elasticsearch

- name: Ensure ElasticSearch is started and enabled to start at boot.
  service: name=elasticsearch state=started enabled=yes

## Greylog

- name: Download the Graylog repository package
  get_url:
    url: 'https://packages.graylog2.org/repo/packages/graylog-2.3-repository_latest.deb'
    dest: '/tmp/graylog_repository.deb'

- name: Install the Graylog repository package
  apt:
    deb: '/tmp/graylog_repository.deb'
    state: installed
    dpkg_options: 'force-all'
  register: install_repo

- name: Install Graylog
  apt: name=graylog-server update_cache={{ update_apt_cache }} state=installed

- name: Copy the Graylog configuration file
  template: src=graylog.server.conf.j2 dest=/etc/graylog/server/server.conf owner=root group=root mode=0644 force=yes
  notify: restart graylog

- name: Ensure Graylog is started and enabled to start at boot.
  service: name=graylog-server state=started enabled=yes
