---
- hosts: lamp-haproxy
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.haproxy

  tasks:
    - name: Ensure socat is installed.
      yum: name=socat state=installed
