---
- name: Create Slack notification script
  become: yes
  template: src=slack-notify.sh.j2 dest=/usr/local/bin/slack-notify.sh
    owner="root" group="root" mode=0700

- name: Add notification to login hook
  lineinfile:
    dest: /etc/pam.d/sshd
    line: "session optional pam_exec.so seteuid /etc/ssh/notify.sh"

# ADD login-notify
# ADD links to PAM login services
