
---
- hosts: all
  vars:
    # variables for Enterprise Linux
    sshd_service_name: sshd
    ssh_owner: root
    ssh_group: root
    ssh_server_hardening:	true	# false to stop harden the server
    ssh_server_revoked_keys: []	# list of revoked public keysto always reject

  tasks:

  - name: bare include default variables
    include_vars: defaults/ssh_hardening.yml

  - name: get openssh-version
    # extract version info from ssh -V
    shell: ssh -V 2>&1 | sed -r 's/.*_([0-9]*\.[0-9]).*/\1/g'
    changed_when: false
    # save as sshd_version
    register: sshd_version
    check_mode: no

  - name: set hostkeys for openssh version greater 6.3
    set_fact:
      ssh_host_key_files: ['/etc/ssh/ssh_host_rsa_key', '/etc/ssh/ssh_host_ecdsa_key', '/etc/ssh/ssh_host_ed25519_key']
    when: sshd_version.stdout >= '6.3' and not ssh_host_key_files

  - name: set hostkeys for openssh version greater 6.0
    set_fact:
      ssh_host_key_files: ['/etc/ssh/ssh_host_rsa_key', '/etc/ssh/ssh_host_ecdsa_key']
    when: sshd_version.stdout >= '6.0' and not ssh_host_key_files

  - name: set hostkeys for openssh version greater 5.3
    set_fact:
      ssh_host_key_files: ['/etc/ssh/ssh_host_rsa_key']
    when: sshd_version.stdout >= '5.3' and not ssh_host_key_files

  - name: create revoked_keys and set permissions to root/600
    become: yes # activate privilege escalation
    template: src='templates/revoked_keys.j2' dest='/etc/ssh/revoked_keys' mode=0600 owner="{{ ssh_owner }}" group="{{ ssh_group }}"
    notify: restart sshd
    when: ssh_server_hardening

  - name: create sshd_config and set permissions to root/600
    ##-CIS 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured: mode=0600
    become: yes # activate privilege escalation
    # Validate:
    # -T Check the validity of the configuration file
    # -f config file
    template: src='opensshd.conf.j2' dest='/etc/ssh/sshd_config' mode=0600 owner="{{ ssh_owner }}" group="{{ ssh_group }}" validate="/usr/sbin/sshd -T -f %s"
    notify: restart sshd
    when: ssh_server_hardening

  - name: create ssh_config and set permissions to root/644
    become: yes # activate privilege escalation
    template: src='templates/openssh.conf.j2' dest='/etc/ssh/ssh_config' mode=0644 owner="{{ ssh_owner }}" group="{{ ssh_group }}"
    when: ssh_client_hardening

  handlers:
  - name: restart sshd
    become: yes # activate privilege escalation
    service: name={{ sshd_service_name }} state=restarted
    when: "(ssh_server_enabled|bool)"
