---
java_packages:
  - openjdk-8-jdk

kibana_version: "4.6.6"
kibana_server_name: elk
kibana_username: kibana
kibana_password: password

nginx_user: www-data
nginx_worker_connections: 1024
nginx_remove_default_vhost: true

logstash_monitor_local_syslog: true
logstash_ssl_key_file: elk-vagrant-example.key
logstash_ssl_certificate_file: elk-vagrant-example.crt

logstash_forwarder_logstash_server: elk
logstash_forwarder_ssl_certificate_file: elk-vagrant-example.crt
logstash_forwarder_files:
  - paths:
      - /var/log/auth.log
    fields:
      type: syslog
