---
- hosts: all

  vars:
    # Disable ctrl-alt-delete key sequence on the console.
    security_rhel7_disable_ctrl_alt_delete: yes
    # Set session timeout.
    security_rhel7_session_timeout: 600

  tasks:

  # This returns an exit code of 0 if it's running, 3 if it's masked.
  - name: Check if ctrl-alt-del.target is already masked
    command: systemctl status ctrl-alt-del.target
    register: cad_mask_check
    check_mode: no
    changed_when: False
    failed_when: cad_mask_check.rc not in [0,3]
    tags:
      - always

  - name: The x86 Ctrl-Alt-Delete key sequence must be disabled
    command: systemctl mask ctrl-alt-del.target
    when:
      - security_rhel7_disable_ctrl_alt_delete | bool
      - cad_mask_check.rc != 3
    notify:
      - reload systemd
    tags:
      - misc

  - name: Set 10min timeout on communication sessions
    blockinfile:
      dest: /etc/profile
      insertbefore: EOF
      marker: "# {mark} MANAGED BY ANSIBLE"
      block: |
        # Set a {{ security_rhel7_session_timeout }} second timeout for sessions
        TMOUT={{ security_rhel7_session_timeout }}
        readonly TMOUT
        export TMOUT

  handlers:
  - name: reload systemd
    systemd:
      daemon-reload: yes
